### ISSUE TITLE
Error in deserialization of ApplicationTypes response

### ISSUE THREAD

**Issue by andradf** [Microsoft/service-fabric-client-dotnet#121]
I have a cluster running SF version 9.1.1653.9590. When I attempt to get the application types using the powershell http service fabric module, I get the following error
`Get-SFApplicationType: Cannot process argument because the value of argument "obj" is null. Change the value of argument "obj" to a non-null value.`

```
StackTrace  :
   at System.Management.Automation.PSObject..ctor(Object obj)
   at Microsoft.ServiceFabric.Powershell.Http.GetApplicationTypeCmdlet.FormatOutput(Object output)
   at Microsoft.ServiceFabric.Powershell.Http.GetApplicationTypeCmdlet.ProcessRecordInternal()
   at Microsoft.ServiceFabric.Powershell.Http.CommonCmdletBase.ProcessRecord()
```

Looking through the code and examining the http response body it seems like the issue is that the client library is deserializing the field `ManagedKeyVaultReferenceParameterList` incorrectly.
The HTTP response contains a property with name `ManagedKeyVaultReferenceParameters` while the deserialization performed in `ApplicationTypeInfoConverter` expects it to be `ManagedKeyVaultReferenceParameterList`.

This leads to the exception in Get-SFApplicationType due to ManagedKeyVaultReferenceParameterList being null instead of an empty array and being passed to the PSObject constructor.

**Comment by jeffj6123** [comment]
@andradf We are looking into this
