### ISSUE TITLE
Get-SFClusterUpgradeProgress : Failed to deserialize json response from server

### ISSUE THREAD

**Issue by K-Cully** [Microsoft/service-fabric-client-dotnet#79]
**Describe the bug**
When calling Get-SFClusterUpgradeProgress against a Cluster in the "Ready" state, the error below is thrown.
Service Fabric version: 6.5.664.9590

```
Get-SFClusterUpgradeProgress : Failed to deserialize json response from server.
At line:1 char:1
+ Get-SFClusterUpgradeProgress
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-SFClusterUpgradeProgress], ServiceFabricException
+ FullyQualifiedErrorId : GetClusterUpgradeProgressErrorId,Microsoft.ServiceFabric.Powershell.Http.GetClusterUpgradeProgressCmdlet
```

**To Reproduce**
Connect to a secure cluster.
Run Get-SFClusterUpgradeProgress

**Expected behavior**
A result is returned to the caller.

**Comment by hbuckle** [comment]
I believe this is a problem with the API - the json response from `GetUpgradeProgress` is below and the `ApplicationHealthPolicyMap` property is wrong, according to the [docs](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-model-clusterupgradedescriptionobject#applicationhealthpolicymap) it should be an array not an object

```json
{
  "CodeVersion": "6.5.676.9590",
  "ConfigVersion": "2",
  "UpgradeDomains": [
    {
      "Name": "0",
      "State": "Completed"
    },
    {
      "Name": "1",
      "State": "Completed"
    },
    {
      "Name": "2",
      "State": "Completed"
    },
    {
      "Name": "3",
      "State": "Completed"
    },
    {
      "Name": "4",
      "State": "Completed"
    }
  ],
  "UpgradeState": "RollingForwardCompleted",
  "NextUpgradeDomain": "",
  "RollingUpgradeMode": "Monitored",
  "UpgradeDescription": {
    "CodeVersion": "6.5.676.9590",
    "ConfigVersion": "2",
    "UpgradeKind": "Rolling",
    "RollingUpgradeMode": "Monitored",
    "UpgradeReplicaSetCheckTimeoutInSeconds": 4294967295,
    "ForceRestart": false,
    "MonitoringPolicy": {
      "FailureAction": "Rollback",
      "HealthCheckWaitDurationInMilliseconds": "PT0H0M30S",
      "HealthCheckStableDurationInMilliseconds": "PT0H1M0S",
      "HealthCheckRetryTimeoutInMilliseconds": "PT0H45M0S",
      "UpgradeTimeoutInMilliseconds": "PT12H0M0S",
      "UpgradeDomainTimeoutInMilliseconds": "PT2H0M0S"
    },
    "ClusterHealthPolicy": {
      "ConsiderWarningAsError": false,
      "MaxPercentUnhealthyNodes": 100,
      "MaxPercentUnhealthyApplications": 0
    },
    "EnableDeltaHealthEvaluation": true,
    "ClusterUpgradeHealthPolicy": {
      "MaxPercentDeltaUnhealthyNodes": 0,
      "MaxPercentUpgradeDomainDeltaUnhealthyNodes": 0
    },
    "ApplicationHealthPolicyMap": {
      "ApplicationHealthPolicyMap": [
        {
          "Key": "fabric:\/System",
          "Value": {
            "ConsiderWarningAsError": false,
            "MaxPercentUnhealthyDeployedApplications": 0,
            "DefaultServiceTypeHealthPolicy": {
              "MaxPercentUnhealthyServices": 0,
              "MaxPercentUnhealthyPartitionsPerService": 0,
              "MaxPercentUnhealthyReplicasPerPartition": 0
            },
            "ServiceTypeHealthPolicyMap": [
              {
                "Key": "ClusterManagerServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "DnsServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "EventStoreServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "FMServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "FaultAnalysisServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "FileStoreServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "NamingStoreService",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "RepairManagerServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "UpgradeServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              }
            ]
          }
        }
      ]
    },
    "SortOrder": "Default"
  },
  "UpgradeDurationInMilliseconds": "PT0H18M1.98432S",
  "UpgradeDomainDurationInMilliseconds": "PT0H0M0.0636127S",
  "UnhealthyEvaluations": [],
  "CurrentUpgradeDomainProgress": {
    "DomainName": "",
    "NodeUpgradeProgressList": []
  },
  "StartTimestampUtc": "2019-12-27T14:15:33.886Z",
  "FailureTimestampUtc": "0001-01-01T00:00:00.000Z",
  "FailureReason": "None",
  "UpgradeDomainProgressAtFailure": {
    "DomainName": "",
    "NodeUpgradeProgressList": []
  }
}
```

Full exception

```
Exception Info: Microsoft.ServiceFabric.Common.Exceptions.ServiceFabricException: Failed to deserialize json response from server.
  ---> Newtonsoft.Json.JsonReaderException: Unexpected JsonToken StartObject.
    at Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.ReadStartArray(JsonReader reader)
    at Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.ReadList[T](JsonReader reader, Func`2 deserializerFunc)
    at Microsoft.ServiceFabric.Client.Http.Serialization.ClusterUpgradeDescriptionObjectConverter.GetFromJsonProperties(JsonReader reader)
    at Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.Deserialize[T](JsonReader reader, Func`2 getFromJsonPropertiesFunc)
    at Microsoft.ServiceFabric.Client.Http.Serialization.ClusterUpgradeDescriptionObjectConverter.Deserialize(JsonReader reader)
    at Microsoft.ServiceFabric.Client.Http.Serialization.ClusterUpgradeProgressObjectConverter.GetFromJsonProperties(JsonReader reader)
    at Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.Deserialize[T](JsonReader reader, Func`2 getFromJsonPropertiesFunc)
    at Microsoft.ServiceFabric.Client.Http.Serialization.ClusterUpgradeProgressObjectConverter.Deserialize(JsonReader reader)
    at Microsoft.ServiceFabric.Client.Http.ServiceFabricHttpClient.SendAsyncGetResponse[T](Func`1 requestFunc, String relativeUri, Func`2 deserializeFunc, String requestId, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at Microsoft.ServiceFabric.Client.Http.ServiceFabricHttpClient.SendAsyncGetResponse[T](Func`1 requestFunc, String relativeUri, Func`2 deserializeFunc, String requestId, CancellationToken cancellationToken)
```

**Comment by hbuckle** [comment]
@amanbha - any update on this? The bug I linked has been closed, but it is still not resolved

**Comment by amanbha** [comment]
@hbuckle are you still able to repro with latest nuget package of client library and latest SF runtime, I will also followup reg. the swagger update\
