### ISSUE TITLE
Unable to use ImageStore Client in .NET API: throws with service not found

### ISSUE THREAD

**Issue by sarahdonofrio** [Microsoft/service-fabric-client-dotnet#84]
I have a .NET API that is connecting to service fabric, I can do all the following:
            var content = await fabricClient.Cluster.GetImageStoreConnectionStringAsync();
            var list = await fabricClient.ApplicationTypes.GetApplicationTypeInfoListAsync();
            var applications =  await fabricClient.Applications.GetApplicationInfoAsync("addc/QueryServiceWatchdogApp");
BUT If I try to do anything with the ImageStore API, it throws with service not found
            **var foldersize = await fabricClient.ImageStore.GetImageStoreRootFolderSizeAsync();**
This goes for upgrading the application as well.

**Comment by amanbha** [comment]
@sarahdonofrio Could you please share the exact error code & exception you are getting

**Comment by sarahdonofrio** [comment]
yep! This is the callstack from postman:
Microsoft.ServiceFabric.Common.Exceptions.ServiceFabricException: Service does not exist.
   at Microsoft.ServiceFabric.Client.Http.ServiceFabricHttpClient.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, Uri requestUri, String clientRequestId, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Client.Http.ServiceFabricHttpClient.SendAsyncGetResponse[T](Func`1 requestFunc, String relativeUri, Func`2 deserializeFunc, String requestId, CancellationToken cancellationToken)
   at Ev2HttpExtension.Controllers.HomeController.PutImageStoreFromBlogStorage() in C:\Users\sadono\source\repos\Ev2HttpExtension\Ev2HttpExtension\Controllers\HomeController.cs:line 43
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 0
Host: localhost:44365
User-Agent: PostmanRuntime/7.6.0
<excluded token>

**Comment by sarahdonofrio** [comment]
@amanbha  that line (43) is simply:
  var foldersize = await fabricClient.ImageStore.GetImageStoreRootFolderSizeAsync();

**Comment by sarahdonofrio** [comment]
Ah I think this is similar to:
All operations on the ImageStore give exceptions when using the client with a dev cluster. (also UploadApplicationPackageAsync)
Microsoft.ServiceFabric.Common.Exceptions.ServiceFabricException: FABRIC_E_SERVICE_DOES_NOT_EXIST. Service does not exist.

The reason is the lack of an ImageStoreService in a dev cluster. It uses the file system instead. The old fabric client api could handle this as you specified the ImageStoreConnectionString (filepath incase of a dev cluster).

Will there come support for the file system imagestore in this client aswell?

**Comment by sarahdonofrio** [comment]
So I think maybe the actual bug is just in the usability of that connection string... if/when I figure it out I'm happy to update comments and some things in the code to make it more understandable for when to use them

**Comment by sarahdonofrio** [comment]
Discussed and this is an unsupported legacy mode we are running (AzureStorage) and our use case is upgrading from AzureStorage
